### ISSUE TITLE
Assertion with negative bounds for Rnd::i32/i64_in

### ISSUE THREAD

**Issue by yrns** [SamiPerttu/funutd#1]
I expected these to work but they both assert with 'assertion failed: max >= min':

```rust
let rnd = Rnd::new();
_ = rnd.i32_in(-1, 1);
_ = rnd.i64_in(-1, 1);
```

Maybe a new implementation is needed for signed integers?

**Comment by SamiPerttu** [comment]
Yikes! Thanks for the report. I committed a fix. I'll release a new version soon, too.
