### ISSUE TITLE
Invalid tRNS length

### ISSUE THREAD

**Issue by yrns** [SamiPerttu/funutd#2]
In trying to use textures generated via the editor in Bevy I get the following error: 

> "Format error decoding Png: Not enough palette entries, expect 6 got 4."

 pngcheck gives a different error: 

> "invalid tRNS length for RGB image"

Most apps I tried open the png fine, but Bevy (nor anything probably using the png crate) does not. I was able to get it working by opening the file in krita and exporting from there.

I don't know much about the png format, but does transparency even make any sense here for textures the editor produces?

**Comment by SamiPerttu** [comment]
Thanks for the report. The tRNS block made no sense indeed so I removed it and released 0.12.1, please upgrade to that version.
